config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_scope :admin do
    get "/login", to: "devise/sessions#new"
  end

  get '/about', to: 'welcome#about'
  get '/data', to: 'datasets#index'

  resources :datasets, only: [:index, :show]
  resources :policies, only: [:index, :show]

  namespace :admin do
    resources :datasets, :policies, :data_groups, :action_links
  end

  root 'welcome#home'
end

app/models/action_link.rb
class ActionLink < ActiveRecord::Base
  has_many :policy_action_links
  has_many :policies, through: :policy_action_links
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/data_group.rb
class DataGroup < ActiveRecord::Base
  has_many :data_group_policies
  has_many :policies, through: :data_group_policies

  has_many :data_group_datasets
  has_many :datasets, through: :data_group_datasets

  belongs_to :parent, class_name: 'DataGroup'
  has_many :children, class_name: 'DataGroup', foreign_key: 'parent_id'

  scope :policy_groups, -> { where(is_super_group: false)}
  scope :super_groups, -> { where(is_super_group: true)}
end

app/models/data_group_dataset.rb
class DataGroupDataset < ActiveRecord::Base
  belongs_to :data_group
  belongs_to :dataset
end

app/models/data_group_policy.rb
class DataGroupPolicy < ActiveRecord::Base
  belongs_to :policy
  belongs_to :data_group
end

app/models/data_groups_datasets.rb
class DataGroupsDatasets < ActiveRecord::Base
  belongs_to :data_group
  belongs_to :dataset
end

app/models/data_groups_policies.rb
class DataGroupsPolicies < ActiveRecord::Base
  belongs_to :policies
  belongs_to :data_groups
end

app/models/dataset.rb
class Dataset < ActiveRecord::Base
  has_many :dataset_policies
  has_many :policies, through: :dataset_policies

  has_many :data_group_datasets
  has_many :data_groups, through: :data_group_datasets
end

app/models/dataset_policy.rb
class DatasetPolicy < ActiveRecord::Base
  belongs_to :dataset
  belongs_to :policy
end

app/models/datasets_policies.rb
class DatasetsPolicies < ActiveRecord::Base
  belongs_to :dataset
  belongs_to :policy
end

app/models/policy.rb
class Policy < ActiveRecord::Base
  has_many :data_group_policies
  has_many :data_groups, through: :data_group_policies
  has_many :policy_action_links
  has_many :action_links, through: :policy_action_links
  has_many :datasets_policies
  has_many :datasets, through: :datasets_policies
end

app/models/policy_action_link.rb
class PolicyActionLink < ActiveRecord::Base
  belongs_to :policy
  belongs_to :action_link
end

app/models/service_or_action_link.rb
class ActionLink < ActiveRecord::Base
  belongs_to :policies
end

app/controllers/admin/datasets_controller.rb
class Admin::DatasetsController < AdminController
  def index
    @resources = Dataset.all
  end

  def new
    @dataset = Dataset.new
  end

  def create
    @dataset = Dataset.new(dataset_params)
    if @dataset.save
      flash[:notice] = "Dataset '#{@dataset.name} was created successfully."
      redirect_to admin_dataset_path(@dataset)
    else
      flash[:errors] = @dataset.errors
      render :new
    end
  end

  def edit
    @dataset = Dataset.find(params[:id])
  end

  def update
    @dataset = Dataset.find(params[:id])
    @dataset.assign_attributes(dataset_params)
    if @dataset.save
      flash[:notice] = "Dataset '#{@dataset.name} was updated successfully."
      redirect_to admin_dataset_path(@dataset)
    else
      flash[:errors] = @dataset.errors
      render :edit
    end
  end

  def show
    @dataset = Dataset.find(params[:id])
  end

  def destroy
    @dataset = Dataset.find(params[:id])
    if @dataset.destroy
      flash[:notice] = "Dataset '#{@dataset.name}' was deleted successfully."
    else
      flash[:errors] = @dataset.errors
    end
    redirect_to :admin_datasets
  end

  private

  def dataset_params
    params.require(:dataset).permit(:name, :chart_title, :notes, :source_description, :source_url, :visualization_iframe)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :verify_is_admin

  def verify_is_admin
    redirect_to(root_path) unless admin_signed_in?
  end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  def index
  end
end

app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  def index
    @data_group_tree = DataGroupService.new(DataGroup.all.includes(:datasets)).tree
    
    respond_to do |format|
      format.html
      format.json { render json: Dataset.all.to_json }
    end
  end

  def show
    @dataset = Dataset.find(params[:id])
    
    respond_to do |format|
      format.json { render json: @dataset }
    end
  end
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  def index
    @policies = Policy.all
  end

  def show
    @policy = Policy.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @policies = Policy.limit(12)
  end

  def about
  end
end

app/helpers/admin/datasets_helper.rb
module Admin::DatasetsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_page(path)
    "active" if current_page?(path)
  end
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/datasets_helper.rb
module DatasetsHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/datasets/_form.html.erb
<div class='form-group'>
  <%= f.label :name, class: 'col-sm-2' %>
  <div class='col-sm-10'>
    <%= f.text_field :name %>
  </div>
</div>
<div class='form-group'>
  <%= f.label :chart_title, class: 'col-sm-2' %>
  <div class='col-sm-10'>
    <%= f.text_field :chart_title %>
  </div>
</div>
<div class='form-group'>
  <%= f.label :source_description, class: 'col-sm-2' %>
  <div class='col-sm-10'>
    <%= f.text_area :source_description, size: '100x5' %>
  </div>
</div>
<div class='form-group'>
  <%= f.label :notes, class: 'col-sm-2' %>
  <div class='col-sm-10'>
    <%= f.text_area :notes, size: '100x5' %>
  </div>
</div>
<div class='form-group'>
  <%= f.label :source_url, class: 'col-sm-2' %>
  <div class='col-sm-10'>
    <%= f.text_field :source_url %>
  </div>
</div>
<div class='form-group'>
  <%= f.label :visualization_iframe, class: 'col-sm-2' %>
  <div class='col-sm-10'>
    <%= f.text_field :visualization_iframe %>
  </div>
</div>
<%= dataset.visualization_iframe.html_safe if dataset.visualization_iframe %>
<br/>

app/views/admin/datasets/edit.html.erb
<div class='container admin'>
  <div class='row'>
    <div class='col-sm-12'>
      <%= form_for @dataset, url: admin_dataset_path(@dataset.id), method: 'PUT', html: { role: 'form', class: 'form-horizontal' } do |f| %>
        <%= render partial: 'form', locals: { f: f, dataset: @dataset } %>
        <%= f.submit 'Update', class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/datasets/index.html.erb
<div class='container admin'>
  <% if !@resources.empty? %>
    <div class='row'>
      <table class='table'>
        <th>Name</th>
        <th>Chart Title</th>
        <th>Source Description</th>
        <th>Notes</th>
        <th>Visualization iFrame</th>
        <th>Source Url</th>
        <th></th>
        <% @resources.each do |resource| %>
          <tr>
            <td><%= truncate resource.name %></td>
            <td><%= truncate resource.chart_title %></td>
            <td><%= truncate resource.source_description, length: 60 %></td>
            <td><%= truncate resource.notes, length: 60  %></td>
            <td><%= truncate resource.visualization_iframe, length: 60  %></td>
            <td><%= truncate resource.source_url, length: 60  %></td>
            <td data-no-turbolink>
              <%= link_to 'Details', admin_dataset_path(resource.id) %>
              <%= link_to 'Edit', edit_admin_dataset_path(resource.id) %>
              <%= link_to 'Delete', admin_dataset_path(resource.id), method: 'Delete' %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  <% end %>
  Create <%= link_to 'a dataset', new_admin_dataset_path %>.
</div>

app/views/admin/datasets/new.html.erb
<div class='container admin'>
  <div class='row'>
    <div class='col-sm-12'>
      <%= form_for @dataset, url: admin_datasets_path, html: { role: 'form', class: 'form-horizontal' } do |f| %>
        <%= render partial: 'form', locals: { f: f, dataset: @dataset } %>
        <%= f.submit 'Create', class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/datasets/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-sm-10'>
      <h2><%= @dataset.name %></h2>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12' data-no-turbolink>
      <h4> <%= link_to 'Edit', edit_admin_dataset_path(@dataset.id) %> | <%= link_to 'Delete', admin_dataset_path(@dataset.id), method: 'Delete' %> </h4>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3>Policy data groups:</h3>
      <% @dataset.data_groups.each do |data_group| %>
        <%= link_to data_group.name, admin_data_group_path(data_group) %> |
      <% end %>
      Edit in the <%= link_to 'Data Groups admin section', admin_data_groups_path %>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3>Source Description</h3>
      <%= @dataset.source_description.html_safe %>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3>Notes</h3>
      <%= @dataset.notes.html_safe %>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3>Source Url</h3>
      <%= link_to @dataset.source_url, @dataset.source_url, target: '_blank' %>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3>Visualization iframe string</h3>
      <%= @dataset.visualization_iframe %>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3>Chart Title</h3>
      <%= @dataset.chart_title.try(:html_safe) %>
    </div>
  </div>
  <%= @dataset.visualization_iframe.html_safe if @dataset.visualization_iframe %>
  <div class='row'>
    <div class='col-sm-12' data-no-turbolink>
      <h4> <%= link_to 'Edit', edit_admin_dataset_path(@dataset.id) %> | <%= link_to 'Delete', admin_dataset_path(@dataset.id), method: 'Delete' %> </h4>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3><%= link_to 'All Datasets', admin_datasets_path %></h3>
    </div>
  </div>
</div>

app/views/datasets/_visualization.html.erb
<div class='row hidden' data-datagroup-dataset-visualization-id=<%= "#{dataset.id}-#{child_data_group[:element].id}" %>>
  <div class='col-sm-12'>
    <div class='visualization'>
      <% if dataset.chart_title.present? %>
        <div class='row'>
          <div class='col-sm-12'>
            <h3><%= dataset.chart_title.try(:html_safe) %></h3>
          </div>
        </div>
      <% end %>
      <%= dataset.visualization_iframe.html_safe %>
      <div class='row'>
        <div class='col-sm-12 description'>
          <%= dataset.source_description.html_safe %>
        </div>
      </div>
      <div class='row'>
        <div class='col-sm-12 notes'>
          <%= dataset.notes.html_safe %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/datasets/index.html.erb
<div class='container-fluid' id='data-browser-masthead'>
  <div class='darkener'></div>
  <div class='container'>
    <h2>Data Browser</h2>
  </div>
</div>
<div class='container clearfix'>
  <div class='row'>
    <div class='col-sm-3'>
      <div class='panel-group' id='data-group-accordion'>
        <% @data_group_tree.each_with_index do |parent_data_group, parent_index| %>
          <div class='panel panel-default parent'>
            <div class='panel-heading'>
              <h4 class='panel-title'>
                <a data-toggle='collapse' data-parent='#data-group-accordion' href='#collapse-<%= parent_index %>'>
                  <%= parent_data_group[:element].name %>
                </a>
              </h4>
            </div>
            <div id='collapse-<%= parent_index %>' class='panel-collapse collapse <%= 'in' if parent_index == 0 %>'>
              <div class='panel-body parent'>
                <div class='panel-group' id='data-panel-subgroup-<%= parent_index %>'>
                  <% parent_data_group[:children].each_with_index do |child_data_group, child_index| %>
                    <div class='panel panel-default'>
                      <div class='panel-heading child'>
                        <h6 class='panel-title'>
                          <a data-toggle='collapse' href='#collapse-<%= "#{parent_index}-#{child_index}" %>'>
                            <%= child_data_group[:element].name %>
                          </a>
                        </h6>
                      </div>
                    </div>
                    <div id='collapse-<%= "#{parent_index}-#{child_index}" %>' class='panel-collapse collapse <%= 'in' if child_index == 0 %>' data-parent='#data-panel-subgroup-<%= parent_index %>'>
                      <ul>
                        <% child_data_group[:children].each do |dataset| %>
                          <li data-datagroup-dataset-id="<%= "#{dataset.id}-#{child_data_group[:element].id}" %>" data-dataset-url="<%= dataset.visualization_iframe %>"><%= dataset.name %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <% if @data_group_tree.first[:children].first[:children].first %>
      <div class='col-sm-9' id='data-browser'>
        <div id='loading'></div>
        <% @data_group_tree.each do |parent| %>
          <% parent[:children].each do |child| %>
            <% child[:children].each do |dataset| %>
              <%= render partial: 'visualization', locals: { dataset: dataset, child_data_group: child } %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<%= javascript_include_tag "cached_iframes.js", :async => true %>