config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_scope :admin do
    get "/login", to: "devise/sessions#new"
  end

  get '/about', to: 'welcome#about'
  get '/data', to: 'datasets#index'

  resources :datasets, only: [:index, :show]
  resources :policies, only: [:index, :show]

  namespace :admin do
    resources :datasets, :policies, :data_groups, :action_links
  end

  root 'welcome#home'
end

app/models/action_link.rb
class ActionLink < ActiveRecord::Base
  has_many :policy_action_links
  has_many :policies, through: :policy_action_links
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/data_group.rb
class DataGroup < ActiveRecord::Base
  has_many :data_group_policies
  has_many :policies, through: :data_group_policies

  has_many :data_group_datasets
  has_many :datasets, through: :data_group_datasets

  belongs_to :parent, class_name: 'DataGroup'
  has_many :children, class_name: 'DataGroup', foreign_key: 'parent_id'

  scope :policy_groups, -> { where(is_super_group: false)}
  scope :super_groups, -> { where(is_super_group: true)}
end

app/models/data_group_dataset.rb
class DataGroupDataset < ActiveRecord::Base
  belongs_to :data_group
  belongs_to :dataset
end

app/models/data_group_policy.rb
class DataGroupPolicy < ActiveRecord::Base
  belongs_to :policy
  belongs_to :data_group
end

app/models/data_groups_datasets.rb
class DataGroupsDatasets < ActiveRecord::Base
  belongs_to :data_group
  belongs_to :dataset
end

app/models/data_groups_policies.rb
class DataGroupsPolicies < ActiveRecord::Base
  belongs_to :policies
  belongs_to :data_groups
end

app/models/dataset.rb
class Dataset < ActiveRecord::Base
  has_many :dataset_policies
  has_many :policies, through: :dataset_policies

  has_many :data_group_datasets
  has_many :data_groups, through: :data_group_datasets
end

app/models/dataset_policy.rb
class DatasetPolicy < ActiveRecord::Base
  belongs_to :dataset
  belongs_to :policy
end

app/models/datasets_policies.rb
class DatasetsPolicies < ActiveRecord::Base
  belongs_to :dataset
  belongs_to :policy
end

app/models/policy.rb
class Policy < ActiveRecord::Base
  has_many :data_group_policies
  has_many :data_groups, through: :data_group_policies
  has_many :policy_action_links
  has_many :action_links, through: :policy_action_links
  has_many :datasets_policies
  has_many :datasets, through: :datasets_policies
end

app/models/policy_action_link.rb
class PolicyActionLink < ActiveRecord::Base
  belongs_to :policy
  belongs_to :action_link
end

app/models/service_or_action_link.rb
class ActionLink < ActiveRecord::Base
  belongs_to :policies
end

app/controllers/admin/data_groups_controller.rb
class Admin::DataGroupsController < AdminController
  def index
    @data_group_tree = DataGroupService.new(DataGroup.all.includes(:datasets)).tree
    @data_groups = DataGroup.all
  end

  def new
    @data_group = DataGroup.new
    @data_groups = DataGroup.all
    @super_data_groups = @data_groups.select { |data_group| data_group.is_super_group? }
    @datasets = Dataset.all
  end

  def create
    data_group = DataGroup.new(data_group_params)
    if data_group_params[:is_super_group] != "0"
      data_group.children = DataGroup.find(params[:data_group][:child_ids]) if params[:data_group][:child_ids]
    else
      data_group.datasets = Dataset.find(params[:data_group][:dataset_ids]) if params[:data_group][:dataset_ids]
    end

    if data_group.save
      redirect_to admin_data_group_path data_group
    else
      flash[:errors] = data_group.errors
      render :new
    end
  end

  def show
    @data_group = DataGroup.includes(:datasets).find(params[:id])
    @children = DataGroup.where(parent_id: @data_group.id)
    @data_group_tree = DataGroupService.new(DataGroup.all.includes(:datasets)).tree
  end

  def edit
    @data_group = DataGroup.find(params[:id])
    @data_groups = DataGroup.all
    @super_data_groups = @data_groups.select { |data_group| data_group.is_super_group? }
    @datasets = Dataset.all
  end

  def update
    data_group = DataGroup.find(params[:id])
    if data_group_params[:is_super_group] != "0"
      data_group.children = DataGroup.find(params[:data_group][:child_ids]) if params[:data_group][:child_ids]
    else
      data_group.datasets = Dataset.find(params[:data_group][:dataset_ids]) if params[:data_group][:dataset_ids]
    end

    data_group.assign_attributes(data_group_params)
    if data_group.save
      flash[:notice] = "Data group '#{data_group.name}' was updated successfully."
      redirect_to admin_data_group_path data_group
    else
      flash[:errors] = data_group.errors
      render :edit
    end
  end

  def destroy
    @data_group = DataGroup.find(params[:id])

    if @data_group.delete
      redirect_to admin_data_groups_path
    else
      flash[:errors] = @data_group.errors
      render admin_data_groups_path
    end
  end

  private

  def data_group_params
    params.require(:data_group).permit(:name, :parent_id, :is_super_group)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :verify_is_admin

  def verify_is_admin
    redirect_to(root_path) unless admin_signed_in?
  end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @policies = Policy.limit(12)
  end

  def about
  end
end

app/helpers/admin/data_groups_helper.rb
module Admin::DataGroupsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_page(path)
    "active" if current_page?(path)
  end
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/datasets_helper.rb
module DatasetsHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/data_groups/_data_group_tree.html.erb
<div class='col-sm-6'>
  <div class='panel-group' id='accordion '>
    <% data_group_tree.each_with_index do |parent_data_group, parent_index| %>
      <div class='panel panel-default parent'>
        <div class='panel-heading'>
          <div class='row'>
            <div class='col-sm-6'>
              <h4 class='panel-title'>
                <a data-toggle='collapse' data-parent='#accordion' href='#collapse-<%= parent_index %>'>
                  <%= parent_data_group[:element].name %>
                </a>
              </h4>
            </div>
            <div class='col-sm-6'>
              <%= link_to 'Show', admin_data_group_path(parent_data_group[:element]) %>
              |
              <%= link_to 'Edit', edit_admin_data_group_path(parent_data_group[:element]) %>
              |
              <%= link_to 'Delete', admin_data_group_path(parent_data_group[:element]), method: 'Delete', confirm: 'Are you sure you want to delete this data group?' %>
            </div>
          </div>
        </div>
        <div id='collapse-<%= parent_index %>' class='panel-collapse collapse in'>
          <div class='panel-body parent'>
            <div class='panel-group' id='data-panel-subgroup-<%= parent_index %>'>
              <% parent_data_group[:children].each_with_index do |child_data_group, child_index| %>
                <div class='panel panel-default'>
                  <div class='panel-heading child'>
                    <div class='row'>
                      <div class='col-sm-6'>
                        <h6 class='panel-title'>
                          <a data-toggle='collapse' href='#collapse-<%= "#{parent_index}-#{child_index}" %>'>
                            <%= child_data_group[:element].name %>
                          </a>
                        </h6>
                      </div>
                      <div class='col-sm-6'>
                        <%= link_to 'Show', admin_data_group_path(child_data_group[:element]) %>
                        |
                        <%= link_to 'Edit', edit_admin_data_group_path(child_data_group[:element]) %>
                        |
                        <%= link_to 'Delete', admin_data_group_path(child_data_group[:element]), method: 'Delete', confirm: 'Are you sure you want to delete this data group?' %>
                      </div>
                    </div>
                  </div>
                </div>
                <div id='collapse-<%= "#{parent_index}-#{child_index}" %>' class='panel-collapse collapse in' data-parent='#data-panel-subgroup-<%= parent_index %>'>
                  <ul>
                    <% child_data_group[:children].each do |dataset| %>
                      <li><%= link_to dataset.name, admin_dataset_path(dataset) %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/data_groups/_form.html.erb
<div class='form-group'>
  <%= f.label :name, class: 'col-sm-2' %>
  <div class='col-sm-10'>
    <%= f.text_field :name %>
  </div>
</div>
<div class='form-group'>
  <div class='col-sm-12'>
    <%= f.check_box :is_super_group, checked: data_group.is_super_group?, data: { on_text: 'Super Group', off_text: 'Policy Group' } %>
  </div>
</div>
<div class='form-group'>
    <div class='col-sm-12'>
      <br/>
      a) <b>For a super group</b>, choose policy data groups <br/>- or -<br/> b) <b>For a policy data group</b>, choose a super group AND datasets
      <br/>
      **<b>Doing both will only recognize the super group selections.</b>**
      <br/><br/>
    </div>
</div>
<div class='panel-group' id='accordion'>
  <div class='panel panel-default parent'>
    <div class='panel-heading'>
      <div class='row'>
        <div class='col-sm-6'>
          <h4 class='panel-title'>
            <a data-toggle='collapse' data-parent='#accordion' href='#collapse-children-selector'>
              <b>Super group</b>: choose policy data groups
            </a>
          </h4>
        </div>
      </div>
    </div>
    <div id='collapse-children-selector' class='panel-collapse collapse <%= 'in' if data_group.is_super_group? %>'>
      <div class='panel-body parent'>
        <div class='form-group'>
          <%= f.label :policy_groups, class: 'col-sm-2' %>
          <div class='col-sm-10'>
            <% @data_groups.each do |child_data_group| %>
              <div class='row'>
                <%= label_tag do %>
                  <%= check_box_tag 'data_group[child_ids][]', child_data_group.id, child_data_group.parent_id == data_group.id && child_data_group.parent_id != nil %>
                  <%= child_data_group.name %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class='panel-heading'>
      <div class='row'>
        <div class='col-sm-6'>
          <h4 class='panel-title'>
            <a data-toggle='collapse' data-parent='#accordion' href='#collapse-parent-and-dataset-selector'>
              <b>Policy data group</b>: choose a super group and datasets
            </a>
          </h4>
        </div>
      </div>
    </div>
    <div id='collapse-parent-and-dataset-selector' class='panel-collapse collapse <%= 'in' if !!data_group.parent_id %>'>
      <div class='panel-body parent'>
        <div class='form-group'>
          <%= f.label :super_groups, class: 'col-sm-2' %>
          <div class='col-sm-10'>
            <% @super_data_groups.each do |parent_data_group| %>
              <div class='row'>
                <%= f.radio_button :parent_id, parent_data_group.id %>
                <%= f.label :parent_id, parent_data_group.name, value: parent_data_group.id %>
              </div>
            <% end %>
          </div>
        </div>
        <hr/>
        <div class='form-group'>
          <%= f.label :datasets, class: 'col-sm-2' %>
          <div class='col-sm-10'>
            <% @datasets.each do |dataset| %>
              <div class='row'>
                <%= label_tag do %>
                  <%= check_box_tag 'data_group[dataset_ids][]', dataset.id, data_group.datasets.include?(dataset) %>
                  <%= dataset.name %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script type='text/javascript'>
  $("[name='data_group[is_super_group]']:visible").bootstrapSwitch();
</script>

app/views/admin/data_groups/edit.html.erb
<div class='container admin'>
  <div class='row'>
    <div class='col-sm-12'>
      <%= form_for @data_group, url: admin_data_group_path(@data_group), method: 'PUT', html: { role: 'form', class: 'form-horizontal' } do |f| %>
        <div class='row'>
          <div class='col-sm-6'>
            <%= f.submit 'Update', class: 'btn btn-default btn-large' %>
          </div>
          <div class='col-sm-6'>
            <h3><%= link_to 'All Data Groups', admin_data_groups_path %></h3>
          </div>
        </div>
        <%= render partial: 'form', locals: { f: f, data_group: @data_group } %>
        <%= f.submit 'Update', class: 'btn btn-default btn-large' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/data_groups/index.html.erb
<br/>
<div class='container'>
  <div class='row'>
    <%= render partial: 'data_group_tree', locals: { data_group_tree: @data_group_tree } %>
    <div class='col-sm-6'>
      <% @data_groups.each do |data_group| %>
        <div class='row'>
          <div class='col-sm-6'>
            <%= link_to data_group.name, admin_data_group_path(data_group) %>
          </div>
          <div class='col-sm-2'>
            <%= data_group.is_super_group? ? 'Super' : 'Policy' %>
          </div>
          <div class='col-sm-4'>
            <%= link_to 'Show', admin_data_group_path(data_group) %> |
            <%= link_to 'Edit', edit_admin_data_group_path(data_group) %> |
            <%= link_to 'Delete', admin_data_group_path(data_group), method: 'Delete' %>
          </div>
        </div>
      <% end %>
      <br/>
      <%= link_to 'Create a new data group', new_admin_data_group_path %>
    </div>
  </div>
</div>

app/views/admin/data_groups/new.html.erb
<div class='container admin'>
  <div class='row'>
    <div class='col-sm-12'>
      <%= form_for @data_group, url: admin_data_groups_path, html: { role: 'form', class: 'form-horizontal' } do |f| %>
        <%= render partial: 'form', locals: { f: f, data_group: @data_group } %>
        <%= f.submit 'Create', class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/data_groups/show.html.erb
<br/>
<div class='container'>
  <div class='row'>
    <%= render partial: 'data_group_tree', locals: { data_group_tree: @data_group_tree } %>
    <div class='col-sm-6'>
      <div class='row'>
        <div class='col-sm-12'>
          <h2><%= @data_group.name %></h2>
        </div>
      </div>
      <div class='row'>
        <div class='col-sm-12'>
          <h3><%= @data_group.is_super_group? ? 'Super Group' : 'Policy Group' %></h3>
        </div>
      </div>
      <% unless @data_group.parent.nil? %>
        <div class='row'>
          <div class='col-sm-12'>
            <h3>Parent</h3>
            <%= link_to @data_group.parent.name, admin_data_group_path(@data_group.parent) %>
          </div>
        </div>
      <% end %>
      <% if @children.any? %>
        <div class='row'>
          <div class='col-sm-12'>
            <h3>Children</h3>
            <% @children.each do |child| %>
              <%= link_to child.name, admin_data_group_path(child) %>
              <br/>
            <% end %>
          </div>
        </div>
      <% end %>
      <% if @data_group.datasets.any? %>
        <div class='row'>
          <div class='col-sm-12'>
            <h3>Datasets</h3>
            <% @data_group.datasets.each do |dataset| %>
              <%= link_to dataset.name, admin_dataset_path(dataset) %>
              <br/>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class='row'>
        <div class='col-sm-12' data-no-turbolink>
          <h4> <%= link_to 'Edit', edit_admin_data_group_path(@data_group.id) %> | <%= link_to 'Delete', admin_data_group_path(@data_group.id), method: 'Delete' %> </h4>
        </div>
      </div>
      <div class='row'>
        <div class='col-sm-12'>
          <h4> <%= link_to 'Create a new data group', new_admin_data_group_path %> </h4>
        </div>
      </div>
      <div class='row'>
        <div class='col-sm-12'>
          <h4> <%= link_to 'Show all data groups', admin_data_groups_path %> </h4>
        </div>
      </div>
    </div>
  </div>
</div>