config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_scope :admin do
    get "/login", to: "devise/sessions#new"
  end

  get '/about', to: 'welcome#about'
  get '/data', to: 'datasets#index'

  resources :datasets, only: [:index, :show]
  resources :policies, only: [:index, :show]

  namespace :admin do
    resources :datasets, :policies, :data_groups, :action_links
  end

  root 'welcome#home'
end

app/models/action_link.rb
class ActionLink < ActiveRecord::Base
  has_many :policy_action_links
  has_many :policies, through: :policy_action_links
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/data_group.rb
class DataGroup < ActiveRecord::Base
  has_many :data_group_policies
  has_many :policies, through: :data_group_policies

  has_many :data_group_datasets
  has_many :datasets, through: :data_group_datasets

  belongs_to :parent, class_name: 'DataGroup'
  has_many :children, class_name: 'DataGroup', foreign_key: 'parent_id'

  scope :policy_groups, -> { where(is_super_group: false)}
  scope :super_groups, -> { where(is_super_group: true)}
end

app/models/data_group_dataset.rb
class DataGroupDataset < ActiveRecord::Base
  belongs_to :data_group
  belongs_to :dataset
end

app/models/data_group_policy.rb
class DataGroupPolicy < ActiveRecord::Base
  belongs_to :policy
  belongs_to :data_group
end

app/models/data_groups_datasets.rb
class DataGroupsDatasets < ActiveRecord::Base
  belongs_to :data_group
  belongs_to :dataset
end

app/models/data_groups_policies.rb
class DataGroupsPolicies < ActiveRecord::Base
  belongs_to :policies
  belongs_to :data_groups
end

app/models/dataset.rb
class Dataset < ActiveRecord::Base
  has_many :dataset_policies
  has_many :policies, through: :dataset_policies

  has_many :data_group_datasets
  has_many :data_groups, through: :data_group_datasets
end

app/models/dataset_policy.rb
class DatasetPolicy < ActiveRecord::Base
  belongs_to :dataset
  belongs_to :policy
end

app/models/datasets_policies.rb
class DatasetsPolicies < ActiveRecord::Base
  belongs_to :dataset
  belongs_to :policy
end

app/models/policy.rb
class Policy < ActiveRecord::Base
  has_many :data_group_policies
  has_many :data_groups, through: :data_group_policies
  has_many :policy_action_links
  has_many :action_links, through: :policy_action_links
  has_many :datasets_policies
  has_many :datasets, through: :datasets_policies
end

app/models/policy_action_link.rb
class PolicyActionLink < ActiveRecord::Base
  belongs_to :policy
  belongs_to :action_link
end

app/models/service_or_action_link.rb
class ActionLink < ActiveRecord::Base
  belongs_to :policies
end

app/controllers/admin/policies_controller.rb
class Admin::PoliciesController < AdminController
  def index
    @resources = Policy.all
  end

  def new
    @policy = Policy.new
    @action_links = ActionLink.all
    @data_groups = DataGroup.policy_groups
  end

  def create
    policy = Policy.new(policy_params)
    if policy.save
      flash[:notice] = "Policy '#{@policy.name}' was saved successfully."
      redirect_to :admin_policies
    else
      flash[:errors] = policy.errors
      render :new
    end
  end

  def edit
    @policy = Policy.where(id: params[:id]).first
    @data_groups = DataGroup.policy_groups
    @action_links = ActionLink.all
    redirect_to :admin_policies if @policy.nil?
  end

  def update
    @policy = Policy.find(params[:id])
    @policy.assign_attributes(policy_params)
    if @policy.save
      flash[:notice] = "Policy '#{@policy.name}' was updated successfully."
      redirect_to :admin_policy
    else
      flash[:errors] = @policy.errors
      render :edit
    end
  end

  def show
    @policy = Policy.includes(:data_groups).find(params[:id])
  end

  def destroy
    @policy = Policy.find(params[:id])
    if @policy.destroy
      flash[:notice] = "Policy '#{@policy.name}' was deleted successfully."
    else
      flash[:errors] = @policy.errors
    end
    redirect_to :admin_policies
  end

  private

  def policy_params
    params.require(:policy).permit(:name, :summary, :description, :organization_text, :resources_text, :thumbnail_image_url, :masthead_image_url, data_group_ids: [], action_link_ids: [])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :verify_is_admin

  def verify_is_admin
    redirect_to(root_path) unless admin_signed_in?
  end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  def index
  end
end

app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  def index
    @data_group_tree = DataGroupService.new(DataGroup.all.includes(:datasets)).tree
    
    respond_to do |format|
      format.html
      format.json { render json: Dataset.all.to_json }
    end
  end

  def show
    @dataset = Dataset.find(params[:id])
    
    respond_to do |format|
      format.json { render json: @dataset }
    end
  end
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  def index
    @policies = Policy.all
  end

  def show
    @policy = Policy.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @policies = Policy.limit(12)
  end

  def about
  end
end

app/helpers/admin/policies_helper.rb
module Admin::PoliciesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_page(path)
    "active" if current_page?(path)
  end
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/datasets_helper.rb
module DatasetsHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/policies/_form.html.erb
<div class='form-group'>
  <%= f.label :name, class: 'col-sm-2' %>
  <div class='col-sm-10'>
    <%= f.text_field :name %>
  </div>
</div>
<div class='form-group'>
  <%= f.label :summary, class: 'col-sm-2' %>
  <div class='col-sm-10'>
    <%= f.text_area :summary, size: '100x5' %>
  </div>
</div>
<div class='form-group'>
  <%= f.label :description, class: 'col-sm-2' %>
  <div class='col-sm-10'>
    <%= f.text_area :description, size: '100x5' %>
  </div>
</div>
<div class='form-group'>
  <%= f.label :data_groups, class: 'col-sm-2' %>
  <div class='col-sm-10'>
    <% data_groups.each do |data_group| %>
      <%= label_tag do %>
        <%= check_box_tag 'policy[data_group_ids][]', data_group.id, policy.data_groups.include?(data_group) %>
        <%= data_group.name %>
      <% end %>
      <br/>
    <% end %>
  </div>
</div>
<div class='form-group'>
  <%= f.label :organization_text, class: 'col-sm-2' %>
  <div class='col-sm-10'>
    <%= f.text_area :organization_text, size: '100x5' %>
  </div>
</div>
<div class='form-group'>
  <%= f.label :resources_text, class: 'col-sm-2' %>
  <div class='col-sm-10'>
    <%= f.text_area :resources_text, size: '100x5' %>
  </div>
</div>
<div class='form-group'>
  <%= f.label :thumbnail_image_url, class: 'col-sm-2' %>
  <%= f.filepicker_field :thumbnail_image_url %>
  <div class='col-sm-2 image-preview'>
    <%= filepicker_image_tag policy.thumbnail_image_url, w: 160, h: 160, fit: 'clip' %>
  </div>
</div>
<div class='form-group'>
  <%= f.label :masthead_image_url, class: 'col-sm-2' %>
  <%= f.filepicker_field :masthead_image_url %>
  <div class='col-sm-2 image-preview'>
    <%= filepicker_image_tag policy.masthead_image_url, w: 160, h: 160, fit: 'clip' %>
  </div>
</div>

<div class='form-group'>
  <%= f.label :action_links, class: 'col-sm-2' %>
  <div class='col-sm-10'>
    <% @action_links.each do |action_link| %>
      <div class='row'>
        <div class='col-sm-12'>
          <%= label_tag do %>
            <%= check_box_tag 'policy[action_link_ids][]', action_link.id, policy.action_links.include?(action_link) %>
            <%= action_link.name %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/policies/edit.html.erb
<div class='container admin'>
  <div class='row'>
    <div class='col-sm-12'>
      <%= form_for @policy, url: admin_policy_path(@policy.id), method: 'PUT', html: { role: 'form', class: 'form-horizontal' } do |f| %>
        <%= render partial: 'form', locals: { f: f, policy: @policy, data_groups: @data_groups } %>
        <%= f.submit 'Save', class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/policies/index.html.erb
<div class='container admin'>
  <% if !@resources.empty? %>
    <div class='row'>
      <table class='table'>
        <th>Name</th>
        <th>Summary</th>
        <th>Description</th>
        <th>Organization Text</th>
        <th>Resources Text</th>
        <th></th>
        <% @resources.each do |resource| %>
          <tr>
            <td><%= truncate resource.name %></td>
            <td><%= truncate resource.summary, length: 60 %></td>
            <td><%= truncate resource.description, length: 60  %></td>
            <td><%= truncate resource.organization_text, length: 60  %></td>
            <td><%= truncate resource.resources_text, length: 60  %></td>
            <td data-no-turbolink>
              <%= link_to 'Details', admin_policy_path(resource.id) %>
              <%= link_to 'Edit', edit_admin_policy_path(resource.id) %>
              <%= link_to 'Delete', admin_policy_path(resource.id), method: 'Delete' %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  <% end %>
  Create <%= link_to 'a policy', new_admin_policy_path %>.
</div>

app/views/admin/policies/new.html.erb
<div class='container admin'>
  <div class='row'>
    <div class='col-sm-12'>
      <%= form_for @policy, url: admin_policies_path, html: { role: 'form', class: 'form-horizontal' } do |f| %>
        <%= render partial: 'form', locals: { f: f, policy: @policy, data_groups: @data_groups } %>
        <%= f.submit 'Create', class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/policies/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-sm-12' data-no-turbolink>
      <h4> <%= link_to 'Edit', edit_admin_policy_path(@policy.id) %> | <%= link_to 'Delete', admin_policy_path(@policy.id), method: 'Delete' %> </h4>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h4>Masthead:</h4>
      <%= filepicker_image_tag @policy.masthead_image_url %>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-2'>
      <%= filepicker_image_tag @policy.thumbnail_image_url %>
    </div>
    <div class='col-sm-10'>
      <h2><%= @policy.name %></h2>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3>Summary</h3>
      <%= @policy.summary.html_safe %>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3>Description</h3>
      <%= @policy.description.html_safe %>
    </div>
  </div>
  <div class='row'>
    <%= render partial: 'policies/data_viewer', locals: { policy: @policy } %>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3>Organization Text</h3>
      <%= @policy.organization_text.html_safe %>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3>Resource Text</h3>
      <%= @policy.resources_text.html_safe %>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3>Action Links</h3>
      <% @policy.action_links.each do |link| %>
        <div class='row'>
          <div class='col-sm-12'>
            <%= link_to link.name, link.url %>
          </div>
        </div>
        <div class='row'>
          <div class='col-sm-12'>
            <%= link.description %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <br/>
  <div class='row'>
    <div class='col-sm-12' data-no-turbolink>
      <h4> <%= link_to 'Edit', edit_admin_policy_path(@policy.id) %> | <%= link_to 'Delete', admin_policy_path(@policy.id), method: 'Delete' %> </h4>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3><%= link_to 'All Policies', admin_policies_path %></h3>
    </div>
  </div>
</div>

app/views/policies/_data_viewer.html.erb
<% if policy.data_groups.any? %>
  <div class='col-sm-2'>
    <div class='panel-group' id='accordion'>
      <% policy.data_groups.each_with_index do |data_group, index| %>
        <div class='panel panel-default parent'>
          <div class='panel-heading'>
            <h4 class='panel-title'>
              <a data-toggle='collapse' href='#collapse-<%= index %>'>
                <%= data_group.name %>
              </a>
            </h4>
          </div>
          <div id='collapse-<%= index %>' class='panel-collapse collapse <%= 'in' if index == 0 %>' >
            <ul>
              <% data_group.datasets.each do |dataset| %>
                <li><%= link_to dataset.name, admin_dataset_path(dataset) %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <% if policy.data_groups.first.datasets.first %>
    <div class='col-sm-10'>
      <div class='row'>
        <div class='col-sm-12'>
          <%= policy.data_groups.first.datasets.first.visualization_iframe.html_safe %>
        </div>
      </div>
      <div class='row'>
        <div class='col-sm-12'>
          <%= policy.data_groups.first.datasets.first.source_description.html_safe %>
        </div>
        <div class='col-sm-12'>
          <%= policy.data_groups.first.datasets.first.notes.html_safe %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/policies/_listing.html.erb
<div class='row' id='policies-listing'>
  <div class='col-sm-12'>
    <% policies.each do |policy| %>
      <%= link_to policy_path policy do %>
        <div class='col-sm-6 policy-preview'>
          <div class='row'>
            <div class='col-sm-2 thumbnail-holder' style='background-image: url(<%= policy.thumbnail_image_url %>)'>
            </div>
            <div class='col-sm-10 policy-summary'>
              <h4><%= policy.name %></h4>
              <p><%= raw(policy.summary) %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/policies/index.html.erb
<div class='container-fluid' id='policies-masthead'>
  <div class='darkener'></div>
  <div class='container'>
    <h2>Policies and Program</h2>
  </div>
</div>
<div class='container'>
  <div class='row'>
    <div class='col-sm-12'>
      <p>Current policies related to affordable housing for the City of San Francisco</p>
    </div>
  </div>
  <%= render partial: 'policies/listing', locals: { policies: @policies } %>
</div>

app/views/policies/show.html.erb
<div class='container-fluid' id='masthead' style='background-image: url(<%= @policy.masthead_image_url %>)'>
  <div class='darkener'></div>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-12'>
        <div class='thumbnail'>
          <%= filepicker_image_tag @policy.thumbnail_image_url %>
        </div>
        <div class='name'>
          <h2><%= @policy.name %></h2>
        </div>
      </div>
    </div>
  </div>
</div>
<div class='container'>
  <div class='row'>
    <div class='col-sm-12'>
      <h3>Summary</h3>
      <%= @policy.summary.html_safe %>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3>Description</h3>
      <%= @policy.description.html_safe %>
    </div>
  </div>
  <div class='row'>
    <%= render partial: 'policies/data_viewer', locals: { policy: @policy } %>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3>Organizations</h3>
      <%= @policy.organization_text.html_safe %>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3>Resources</h3>
      <%= @policy.resources_text.html_safe %>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3>Service and Action Links</h3>
      <div class='action-link-buttons'>
      <% @policy.action_links.each do |action_link| %>
        <%= link_to action_link.url, target: '_blank' do %>
          <button class='btn btn-success'>
            <%= action_link.name.html_safe %>
          </button>
        <% end %>
      <% end %>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12'>
      <h3><%= link_to 'All Policies', admin_policies_path %></h3>
    </div>
  </div>
</div>