config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_scope :admin do
    get "/login", to: "devise/sessions#new"
  end

  get '/about', to: 'welcome#about'
  get '/data', to: 'datasets#index'

  resources :datasets, only: [:index, :show]
  resources :policies, only: [:index, :show]

  namespace :admin do
    resources :datasets, :policies, :data_groups, :action_links
  end

  root 'welcome#home'
end

app/models/action_link.rb
class ActionLink < ActiveRecord::Base
  has_many :policy_action_links
  has_many :policies, through: :policy_action_links
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/data_group.rb
class DataGroup < ActiveRecord::Base
  has_many :data_group_policies
  has_many :policies, through: :data_group_policies

  has_many :data_group_datasets
  has_many :datasets, through: :data_group_datasets

  belongs_to :parent, class_name: 'DataGroup'
  has_many :children, class_name: 'DataGroup', foreign_key: 'parent_id'

  scope :policy_groups, -> { where(is_super_group: false)}
  scope :super_groups, -> { where(is_super_group: true)}
end

app/models/data_group_dataset.rb
class DataGroupDataset < ActiveRecord::Base
  belongs_to :data_group
  belongs_to :dataset
end

app/models/data_group_policy.rb
class DataGroupPolicy < ActiveRecord::Base
  belongs_to :policy
  belongs_to :data_group
end

app/models/data_groups_datasets.rb
class DataGroupsDatasets < ActiveRecord::Base
  belongs_to :data_group
  belongs_to :dataset
end

app/models/data_groups_policies.rb
class DataGroupsPolicies < ActiveRecord::Base
  belongs_to :policies
  belongs_to :data_groups
end

app/models/dataset.rb
class Dataset < ActiveRecord::Base
  has_many :dataset_policies
  has_many :policies, through: :dataset_policies

  has_many :data_group_datasets
  has_many :data_groups, through: :data_group_datasets
end

app/models/dataset_policy.rb
class DatasetPolicy < ActiveRecord::Base
  belongs_to :dataset
  belongs_to :policy
end

app/models/datasets_policies.rb
class DatasetsPolicies < ActiveRecord::Base
  belongs_to :dataset
  belongs_to :policy
end

app/models/policy.rb
class Policy < ActiveRecord::Base
  has_many :data_group_policies
  has_many :data_groups, through: :data_group_policies
  has_many :policy_action_links
  has_many :action_links, through: :policy_action_links
  has_many :datasets_policies
  has_many :datasets, through: :datasets_policies
end

app/models/policy_action_link.rb
class PolicyActionLink < ActiveRecord::Base
  belongs_to :policy
  belongs_to :action_link
end

app/models/service_or_action_link.rb
class ActionLink < ActiveRecord::Base
  belongs_to :policies
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :verify_is_admin

  def verify_is_admin
    redirect_to(root_path) unless admin_signed_in?
  end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_page(path)
    "active" if current_page?(path)
  end
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/datasets_helper.rb
module DatasetsHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_admin_links.html.erb
<%# navigation only for admin users%>
<% if admin_signed_in? %>
  <div id="admin-navigation">
    <div class="container">
      <div class='row'>
        <div class='col-sm-5'>
          <div class="navbar-header">
            Logged in as admin user:
            <%= current_admin.email %>
          </div>
        </div>
        <div class='admin-links'>
          Admin links:
          <ul>
            <li><%= link_to 'Policies', admin_policies_path %></li>
            <li><%= link_to 'Datasets', admin_datasets_path %></li>
            <li><%= link_to 'Data Groups', admin_data_groups_path %></li>
            <li><%= link_to 'Action Links', admin_action_links_path %></li>
            <li><%= link_to 'Logout', destroy_admin_session_path, :method => :delete %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="text-center">
  <div class='container'>
    <div class="row">
      <div class="col-lg-12">
        <ul class="nav nav-pills nav-justified">
          <li><a href="/">A project of #DataSF</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Something here</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <div class="container">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= render 'layouts/admin_links' %>
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'SF Housing Primer', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li class= "<%=active_page(root_path)%>">
  <%= link_to 'Home', root_path %>
</li>
<li class= "<%=active_page(policies_path)%>">
  <%= link_to 'Policies & Programs', policies_path %>
</li>
<li class= "<%=active_page(data_path)%>">
  <%= link_to 'Data Browser', data_path %>
</li>
<li class= "<%=active_page(about_path)%>">
  <%= link_to 'About', about_path %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Housing Policy Guide" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Housing Policy Guide" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= filepicker_js_include_tag %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
      <footer>
        <%= render 'layouts/footer' %>
      </footer>
    </main>
  </body>
</html>